### ISSUE TITLE
Munki 3 tracking

### ISSUE THREAD

**Issue by keeleysam** [munki/munki#563]
It's time to start thinking about the next major release of Munki.

I have started work on this in the branch `munki3` https://github.com/munki/munki/tree/munki3

Goals:
- [x] Move code from `/usr/local/munki` to `/Library/Application Support/munki/bin` which is an Apple supported location and will not be interfered with by Homebrew. Symlink old directory if present, and perhaps move data from `/Library/Managed Installs` to `/Library/Application Support/munki/data`. *
- [x] Update CSS to be in line with current OS X design.  This likely needs a redo of all current CSS work as we do not have the original. #504 
- [ ] Support for featured items on the front page of Managed Software Center, this currently displays a potentially very long list of all items.
- [x] Better secure defaults (No ATS hacks, no default of http://munki/) *
- [x] New MunkiStatus view #436
- [ ] Ability to use more than one of `installcheck_script`, `installs`, and `receipts`. #488 

Other potential items:
- [ ] Code cleanup and more extensive tests.
- [x] <s>Deprecate support for older operating systems (10.6 through 10.8) if this allows for enhanced security, allows for a more rapid release cycle, or otherwise. *</s>
- [x] <s>Rename bundles and launchd items from `com.googlecode.munki.%` to `org.munki.%` *</s>
- [ ] Support for code signing catalogs and manifests in order to better verify source rather than just TLS.

`*` = potential breaking change if one uses custom code, but otherwise should be able to continue working without issue.

**Comment by n8felton** [comment]
I have been looking forward to this for so long.

**Comment by bochoven** [comment]
Not sure about moving from /usr/local which also is an 'Apple supported location' and is the preferred location for unix binaries/scripts.

I would also propose 'live search' or 'search suggestions' while typing in the search box.

**Comment by gregneagle** [comment]
@n8felton: You've been looking forward to _what_ for so long? A "3" after Munki? Thinking about the next major release of Munki?

@bochoven: I'm not that excited about moving away from /usr/local, but Homebrew's bad behavior may force our hand. I think at the least, pre- and postflight scripts must move out of /usr/local/munki, and /usr/local/munki might remain as a symlink to the "new" location (if there is one) -- and all internal tool references will be to the new location.

@keeleysam: "Rename bundles and launchd items from com.googlecode.munki.% to org.munki.% *" seems far more trouble than it is worth:

- Renaming the launchd items (but making no other changes) will force an upgrade of Munki to require a restart for no good reason.
- Changing the preference domains will break users of `manifestutil`, `munkiimport`, and `makecatalogs` unless we also write and test code to move existing prefs from the old domain to the new one. And if anyone is using MCX or config profiles, it gets even harder to do correctly.
- Using the "org.munki*" reverse domain requires the continued goodwill and attention of one Sam Keeley...

**Comment by n8felton** [comment]
FWIW (because apparently I'm the mood to share my opinions today), I agree with one of @keeleysam's comments earlier in Slack: 

> it really needs to move out of `/usr/local` and I figure that if you’re going to break some things you might as well break a bunch at once

So, if we're going to break a bunch of things at once, I'm a huge fan of updating things that appear stuck in time. Most notably, I like the ideas of

> Rename bundles and launchd items from com.googlecode.munki.% to org.munki.%

and

> /Library/Managed Installs to /Library/Application Support/munki/data

As @gregneagle has pointed out, there are some things that are going to break if that happens, but he's already helped identify what those things are so we can a) make sure people know about them if/when they upgrade to Munki 3 and/or b) there can be additional helper code to help with a migration. Yes, there are probably things that are going to break, but that's the beauty of an open source community; people (hopefully) know it's coming and they can plan for it. Major version releases should be treated by "end users" as if nothing from the previous version will work, but if it does, cool.

I'd even add some other renames (or at least additional symlinks or aliases or something) like `managedsoftwareupdate` (because who actually enjoys typing that whole thing out when bash completion isn't configured yet). Personally, I'd enjoy the munki binaries being rolled into something similar to AutoPkg (as long as we can agree on common `<verb>-<noun>` or `<noun>-<verb>` commands and not a mix of both).

```
munki import
munki run (managedsoftwareupdate)
munki make-catalogs
```

There, that's some of my $0.02 worth of a brain dump. More to come later, I'm sure.

**Comment by gregneagle** [comment]
While I understand the appeal of a `munki <verb>` syntax, (I was the one who implemented this functionality in autopkg!), it's unlikely I'll go that route with Munki. Some big reasons off the top of my head:

- A change like this would make tons of existing documentation (much of which I have no control over) immediately useless.
- Many add-on tools for Munki would have to be updated -- again, some of these tools I have no control over
- `munki <verb>` syntax would require further integration/dependency of the existing tools. `makecatalogs`, for example, can run on Linux -- it's not dependent on anything OS X-specific. That's not the case with most of the other tools. (I'd have to look at `manifestutil` -- there's no reason I can think of that it should be dependent on OS X, either) Integrating/combining the tools would make running some bits on Linux more difficult.

(and before anyone suggests that Munki 3 could support the "old" syntax and also the "new" proposed syntax -- that's just more code paths to write, test, and maintain -- is that really worth it?)

Yes there are things I would do differently if I was starting over from scratch with Munki. But we're not starting from scratch -- there's a non-trivial history here.

**Comment by gregneagle** [comment]
"As @gregneagle has pointed out, there are some things that are going to break if that happens" -- I think a far better goal is to NOT introduce breaking changes unnecessarily. Changing `launchd` and `defaults` identifiers just because someone doesn't like the current ones does not meet my definition of a necessary change. It's a proposed change that does not improve functionality, but causes pain.

**Comment by bochoven** [comment]
Wouldn't it be less work to fix the homebrew installer?

**Comment by gregneagle** [comment]
It seems the Homebrew folk have no interest in that.

**Comment by natewalck** [comment]
For relocation, two things come to mind.

1. Where munki lives should be a global var and not be hard coded anymore.

2. We really need to talk to Apple and figure out a future safe location.
Application Support may seem safe, but without confirming we cannot know
for sure.


#1 would allow people to install anywhere they want in the future (like
/opt). I think if we have this type of global, the default can be anywhere
that is safe. The vast majority of munki folks will use the  default, but
being able to change it easily if Apple locks something down has a lot of
utility.
Nate

**Comment by bochoven** [comment]
/LibraryFrameworks ? I hate the space in /L/AS

**Comment by gregneagle** [comment]
"Where munki lives should be a global var and not be hard coded anymore." How would this be communicated to other tools that use/reference the Munki tools -- especially the launchd jobs?

**Comment by natewalck** [comment]
Good point. It may be OK to hardcode it in the default package as provided.
Anyone who is customizing will know what to do.

If Apple screws us, it can be changed in the default pkg if needed.

Nate

**Comment by gregneagle** [comment]
We are already using /Library/Managed Installs (which. sadly, has a space). I don't (yet) see a compelling reason to find a new place under /LIbrary.

**Comment by weswhet** [comment]
Would love to add the ability to String together install check functions as mentioned here. https://github.com/munki/munki/issues/488

**Comment by gregneagle** [comment]
I was looking this over again. I think the road to Munki 3 will be gradual and evolutional, not revolutional. We'll make gradually changes in Munki 2.7, 2.8, etc. Unlike a commercial product, there's no need to "hold back" features in order to make a bigger splash at release to goose sales.

Certainly I would hold back any _breaking_ changes for a 3.0 release, but I want to very seriously consider whether any of the so-far-proposed breaking changes are actually necessary.

**Comment by atoss** [comment]
Wow, looks like Munki 3 has come a long way since this milestone was last updated!  I have a question about one new feature that could be very useful for my deployments.  I have a question about the _Removal of Unused Software_ feature.  It's actually not so much about the removal of the software, but instead I'd like to know if I'll be able to query Munki to see the tracked application usage.  I'd like to use that feature to create a report at the end of the school year for how often each installed application was used.  Will it track all apps or just the ones in Optional Installs?  I see that you can only _remove_ optional installs, but I wonder if all apps can be tracked regardless of whether or not their optional?

**Comment by gregneagle** [comment]
Seems like a really good question for the munki-dev list.

**Comment by gregneagle** [comment]
I'm closing this old issue which isn't really connected to the current Munki 3 development.
